### ISSUE TITLE
您好，请问这个报错怎么解决呢?

### ISSUE THREAD

**Issue by sanyouwu** [cryer/face_recognition#1]
UnicodeError: Unpickling a python object failed: UnicodeDecodeError('ascii', b'IW\xc0\xbbX\x1d\x7f<\x7f\xf0\xa3;5:\x81\xbb\x9b\x06>;L\x8d\x0c=j$%\xbb\xf4[\x9a\xbcq\xa7k\xbc\xe2#&\xbc\xa8W\x04;O\xa6\xd7;\xa1\x9c\xc8\xbb\xd1+\x17\xbc\xa1Y\x00\xba\x80\x9e3;U\x07\r\xbc\xf6\xeaJ>m\x897\xbd\x11\xd2D\xbd \xf2\x1b;\x1f\xb7f\xbal\xc92\xbcU\xac\xc9;\xd5\x97\x9f\xbb\xb6\xec(;a\xc5\x1f\xbd\x8d\xbd"\xbe4$\x81;\x07\x7f\xe7;5L\xa7; \x07\xf7<\x96\xa0\r\xbcR\x11\x1b<+8\xa6;"<\xf8\xbb5\x03M:\x07\xe5\xea:\x9drb\xbd\x16p&=W\x9f\xc4\xbb\x06\xc1\x89\xbc\xd2\x17\x82\xbbf\xc22<\xae\x9f1:\xed\x10\x9b=\xfc\xb9K9\xbe\xff\xe6;"\x90\xc9\xbb\x11\xd0D>6\xf1\x01\xbeS\xefx\xbcz \xb9;\xe7<\x8e\xbb\xb2\xc7\xa3\xbc\x8cH\x1b<\nT\x81\xbbO\xb8\xfd;w\xc9\xc0\xbd\xe0\x89\xbb=Vw\x84;N\x03\x96;<sJ;Z\xaf\xbd\xbc\xfa\x02\x97;\x95}\x97<\x0fR\x12\xbc\xe3:$<k\xea\x86;\xfeo\xe3;\xb1\xbf\x0e<yG\xcb\xbd\x9cEm<*\xe3\x8f;\x04\x1a\x87<\xabe\xb7\xbb\xfb\xef\xa3;(\x87\x1f<\x91Y\xae:\x84\xbb\xb1:v\xa6\x1a<\xbe\xf5\x91=Zu\x0b>\x02i\x94\xbb\xe8\xde\xa2\xbb!\xcb\r;pd\x04<\xa9\xd3\x8e\xbbX7\x8f;\x9b&\xc3<o\x9e\x0f\xbe\x9b\xb2_\xbd\xa6t\xb1\xbaV\x1b\x84\xbb\x86\x95\x9a\xba%#@=\x87\xf0\xc2;\xc5\r\x7f<\xa3\xdd\x00\xbc\xf8\x8f\x14<*\xe5\x19;E\n\x0f\xbd\xfc\x0b:\xbd\xaeW \xbd\xf4)!=\x1a0\xbf\xb8D\x9f\x9e<\xb5\x80A\xbc\xb9I\x1b<\xd5:\xf1=\xe1\x01\xb9:\xae\x1d\xae;\xc3g\xc9;\xa4\\m\xbd!*H\xbd\x83\x91\xd0<Wa\xef\xbb\xc9\x8d\x08<\x11\x12\xb2;\xa9~\xc3\xbbY\x8d1<\xd9X\xb3<&R\x06\xbe\xb7\xbc >xZT;\x89\xa8\xed\xbbEL\x88\xbb4k\x97<', 2, 3, 'ordinal not in range(128)')
You may need to pass the encoding= option to numpy.load

**Comment by cryer** [comment]
看这个错误肯定是编码问题，问题应该出在detect_face.py里加载numpy二进制文件det1.npy.det2.npy,det3.npy那里，具体应该是61行``` data_dict = np.load(data_path, encoding='latin1').item()```,正常来说latin1都是没问题的，至少我是这样的，我是python3.5，numpy1.13.3，不知道你是python2.X还是3.X，2.X的编码默认ASCii码，3.X默认UTF8，而Latin1编码是ASCii的扩展，兼容的，所以正常来说都是没问题的，一般加载出错，也只需要把encoding改成Latin1就好了，但是你既然出错了，那就尝试改成```encoding='bytes' ```试试。不行就python版本和我同步一下应该就没问题了。

**Comment by sanyouwu** [comment]
根据您的回答，已成功解决问题，非常感谢；我配置是anaconda python3.6 numpy 1.14.0。     image_size = 182
input_image_size = 160  
再请问您一下，这两个图片大小为啥这样定呢....？ @cryer

**Comment by cryer** [comment]
这两个其实都是相对随便设定的， image_size = 182是因为在Make_aligndata.py中，我把从摄像头拍的照片(640\*480，不同摄像头不一样)中人脸扣下来之后重新resize成182了，input_image_size = 160则是因为我在Make_classifier.py中将resize后的182\*182的人脸中心剪裁160\*160输入facenet得到编码（*这里编码的大小是由输入尺寸决定的，因为卷积不在意输入尺寸，仅仅输出尺寸会改变而已,代码中``` embedding_size = embeddings.get_shape()[1]```就是获取此时的输出尺寸，所以你也不用在意尺寸问题*），然后编码输入分类器训练。你可以在这两个文件中修改这两个数值，只要后者比前者小就可以了，没有什么强制性的原因。只要记得在上面两个文件中修改完尺寸后，在实时检测的代码中也要修改，确保facenet得到的编码大小和分类器的输入尺寸是一样的。

**Comment by sanyouwu** [comment]
好的，理解了，谢谢您的回答。
