### ISSUE TITLE
Recognition problem.

### ISSUE THREAD

**Issue by ViousGod** [cryer/face_recognition#3]
不好意思

我已經照您給的方法去建立input and output
也順利跑出我的pkl檔

但是為何在執行realtime_face.py時會把我標記成您的姓名呢？

**Comment by cryer** [comment]
[代码](https://github.com/cryer/face_recognition/blob/master/realtime_facenet.py#L31)
这行代码需要修改成你自己和你朋友的名字，注意和你分类器的类别索引顺序一致

**Comment by ViousGod** [comment]
THX!
I did it!
