### ISSUE TITLE
請問有辦法新增"Unknown"的類別嗎?

### ISSUE THREAD

**Issue by ViousGod** [cryer/face_recognition#4]
想將不認識的人標示為Unknown，請問作業上會很困難嗎?

**Comment by cryer** [comment]
你好，如果想不认识的人标记Unknow的话，可能需要修改分类器，判断类别的时候设定一个阈值，概率高于这个阈值才分类，低于这个阈值判定为Unknow。不过，最好使用距离度量的方法，可以参考Andrew Ng的深度学习课程中facenet的部分，经过facenet编码后，通过度量未知图像和库中已知图像的编码的距离来判断类别，同样需要一个阈值，若这个图像的编码和库中所有编码的距离都大于这个阈值，判定为不属于库中任何一个人，即Unknow。否则，判断为距离最小的那个类别。

**Comment by ViousGod** [comment]
感謝你的建議，我之後會試看看，如有成功也會分享，謝謝!

**Comment by ViousGod** [comment]
另外，是不是將輸入給facenet的圖像大小設定為96x96會比較好?
因為facenet輸入端是96x96x3。

**Comment by cryer** [comment]
可以试试

**Comment by umernaeem217** [comment]
> 感謝你的建議，我之後會試看看，如有成功也會分享，謝謝!

Did you get any solution for the unknown?
